/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WebApp1;

import java.util.ArrayList;
import java.util.Arrays;


public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static boolean containsmultiplication(ArrayList<Integer> array,int a,int b,int c){
        for(int i: array) if (i==(a*b*c)) return true;
        return false;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
